### ISSUE TITLE
Option to retract keyboard

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-iOS#103]
In the onboarding permissions setup, if I click on the data storage option, a keyboard pops up which blocks the Next button.

So I have to go back a panel and go forward in order to access the button.

I think there is some way to have a Done button or similar by the keyboard to retract the keyboard:
https://stackoverflow.com/questions/30985870/ios-keyboard-done-button-load-action

A similar change should be made in other parts of the app like the symptom tracker when entering information in the form.

![IMG-2346](https://user-images.githubusercontent.com/174899/81131481-2878d180-8f00-11ea-91cd-f7149146a573.PNG)

**Comment by cheng-tan** [comment]
This setting will be removed once we have delete records button. Related to #58

**Comment by cheng-tan** [comment]
Replaced input box with log delete button, closing this issue
