### ISSUE TITLE
Minor typographic adjustments

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-iOS#106]
In Onboarding:
Self-care tips: "Take care of yourself and others Get self-care tips,"
[There should be a period after 'others']

In resources, there should be a link to King County instead of NYC (refer to Android app).

In Symptom Tracker form at the top there should be a short paragraph (refer to Android app):
Stop and call 911 if you are experiencing:\n
        • Severe, constant chest pain or pressure\n
        • Extreme difficulty breathing\n
        • Severe, constant lightheadedness\n
        • Serious disorientation or unresponsiveness

**Comment by cheng-tan** [comment]
Outdated, closing
