### ISSUE TITLE
Setting up localization infrastructure for iOS

### ISSUE THREAD

**Issue by cheng-tan** [covidsafe/App-iOS#122]
Show resources links base on user's location

**Comment by bananateg** [comment]
I am working at this bug

**Comment by cheng-tan** [comment]
@bananateg this issue is showing different resources links in resource module. For example, if I'm in Washington state, it shows King County health link, if I'm in New York State, it shows New York state link. But we don't have a pool of links yet. 

We also need to support localizing this app in different languages, I guess you might think what this issue is about? Do you want to set up the infrastructure for i18n and pull the strings into a separate message file?

**Comment by bananateg** [comment]
Ok yes

**Comment by cheng-tan** [comment]
Hi @bananateg since android side already has done localization, we want to use the same resource id on iOS side, it's easier for translator(here is the android side localization file https://github.com/covidsafe/App-Android/blob/master/app/src/main/res/values/strings.xml). 

The first step will be setting up the localization infrastructure and send out a PR. The second step would be converting that xml file to json(we can help you do that) then pulling out the text string from each component and replace with the same id from android side. 

I'm not sure what's your bandwidth like, do you have an estimation on how long it will take?
