### ISSUE TITLE
Bluetooth Tracing BLE iOS Native code

### ISSUE THREAD

**Issue by LnJam** [covidsafe/App-iOS#189]
I have a question regarding BLE native code for iOS that is implemented in this library.

1) Is BLE native code for iOS is still integrated in this library?

2) if BLE native code for Bluetooth tracing is removed in iOS than what alternative is being used for Bluetooth tracing ?

Regards

**Comment by cheng-tan** [comment]
Hi @LnJam, BLE implementation has been removed from this app. We have a separate app for BLE(https://github.com/covidsafe/CovidShieldExposure) using Apple Google Exposure notification api.
