### ISSUE TITLE
[Onboarding - Story panes] Content updates

### ISSUE THREAD

**Issue by nessamilan** [covidsafe/App-iOS#213]
Version: 1.11

**Panel 1**
Title: Welcome to CommonCircle Assist
Description: **CommonCircle Assist** helps you protect yourself from risks and stay up to date on what’s happening near you,  take care of yourself if you get sick, and record information that can help protect others if you get ill.

**Panel 2**
Title: Stay informed
Description: Get notifications about locations near you where there’s a risk of COVID-19 exposure. You’ll also get critical alerts from your local health department, such as closures or cleanings of public spaces nearby.

**Panel 3**
Title: Care for yourself
Description: Get tips on managing your symptoms, connect with a healthcare professional if they worsen, and report locations you visited recently to protect others.

**Panel 4**
Title: Your privacy
Description: Any information you log in CommonCircle Assist is protected. Learn more about our approach on privacy in our FAQ.
**Note**: _FAQ_ is a link: https://commoncircle.us/FAQ.html

**Panel 5**
No content change, but the "Privacy | Terms and Conditions" need to be removed, as the privacy link is now on Panel 4.

**Comment by nessamilan** [comment]
Updated in PR: #297

**Comment by cheng-tan** [comment]
To do: 
- [x] add privacy panel
- [x] remove privacy link from last panel
