### ISSUE TITLE
[Onboarding - Story panes] Update privacy link to FAQ on website

### ISSUE THREAD

**Issue by nessamilan** [covidsafe/App-iOS#217]
_**User privacy feature requirement**_

Privacy link is now in story pane 4. Until we have an official privacy statement (product release), we will link to "FAQ", which contains information about our privacy approach:

https://commoncircle.us/FAQ.html

Related to #213

**Comment by cheng-tan** [comment]
Do we still have privacy link in onboarding module? It's been removed from design. Also what's the link for privacy terms?

**Comment by nessamilan** [comment]
@cheng-tan yes, the privacy link is now on Panel 4 as part of the content updates in #213
