### ISSUE TITLE
[Settings] Missing “Control your data storage” feature

### ISSUE THREAD

**Issue by nessamilan** [covidsafe/App-iOS#258]
Version 1.09

Remove "length of data storage" and update with "Control your data storage"

**Build**
<img width="263" alt="Screen Shot 2020-07-09 at 3 25 03 PM" src="https://user-images.githubusercontent.com/6819397/87096767-647a2c80-c1f8-11ea-9bb6-13cff9eb49d6.png">

**Expected**
<img width="488" alt="Screen Shot 2020-07-09 at 3 23 22 PM" src="https://user-images.githubusercontent.com/6819397/87096777-6ba13a80-c1f8-11ea-82b3-86ab857579b3.png">

**Comment by cheng-tan** [comment]
@nessamilan This is released in 1.11 build. Closing this issue.
