### ISSUE TITLE
[Home Tab] Self Care Tips module missing from home tab

### ISSUE THREAD

**Issue by nessamilan** [covidsafe/App-iOS#282]
**Expected** 
Positioned between symptoms and resources:

<img width="269" alt="Screen Shot 2020-07-13 at 3 26 29 PM" src="https://user-images.githubusercontent.com/6819397/87359750-4de81400-c51d-11ea-87a9-443f66c22dd4.png">

**Comment by cheng-tan** [comment]
waiting for the updated icons and content for "wear a mask"
