### ISSUE TITLE
Update Restore Identifier Key?

### ISSUE THREAD

**Issue by ApolloZhu** [covidsafe/App-iOS#35]
Maybe we should consider updating `tracedefense` to `covidsafe` before releasing the app?

https://github.com/covidsafe/App-iOS/blob/813ff356ec6ce4bef61cc373296f7689ab4ab3a6/ios/BLE.mm#L502

https://github.com/covidsafe/App-iOS/blob/813ff356ec6ce4bef61cc373296f7689ab4ab3a6/ios/BLE.mm#L511

**Comment by kumpera** [comment]
This was fixed yesterday.
