### ISSUE TITLE
Retention period rework

### ISSUE THREAD

**Issue by kumpera** [covidsafe/App-iOS#58]
Remove the option to change retention period.
Ensure we have a way to purge logs.

This applies to BLE and location.

**Comment by ApolloZhu** [comment]
Does this mean we'll always use 14 days as the log window?

**Comment by kumpera** [comment]
So far, the consensus is to remote the option from BLE contacts and seed generation only.

**Comment by cheng-tan** [comment]
ble side: #131

**Comment by cheng-tan** [comment]
Delete log button is implemented, purge logs older than 14 days is tracked with #206 . Closing this issue.
