### ISSUE TITLE
Maybe integrate with Azure app analytics 

### ISSUE THREAD

**Issue by kumpera** [covidsafe/App-iOS#60]
Using app analytics would be really useful, but it's problematic from the privacy perspective.

We should consider the benefits before enabling such service.

**Comment by kevinwallace** [comment]
This was integrated in #111.  Is this going to be shipping in the public release?  As you note, collection of analytics is problematic from a privacy perspective.

**Comment by kumpera** [comment]
The plan is to ship it but we should add an opt-in / opt-out setting to the app.

**Comment by kevinwallace** [comment]
#136 is merged, and analytics is opt-in on iOS.  Thank you both for being receptive to a random stranger's privacy concerns!
