### ISSUE TITLE
[Contact Tracing] Apple x Google Exposure Notification Framework

### ISSUE THREAD

**Issue by ApolloZhu** [covidsafe/App-iOS#66]
Documentation: https://developer.apple.com/documentation/exposurenotification
Analysis: https://nshipster.com/contact-tracing/

### Concerns 

In the [FAQ](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-FAQv1.0.pdf), Apple states:

> In keeping with our ***privacy guidelines***, Apple and Google will not receive identifying information about the user, ***location data***, or information about any other devices the user has been in proximity of. 

> Apps will receive approval based on a specific set of criteria designed to ensure they are only
administered in conjunction with public health authorities, ***meet our privacy requirements***, and protect user data.

**Comment by justinklchan** [comment]
@ApolloZhu post this to the Slack and alert others. Do you know if Google has released a framework for Android. We need to begin thinking about how to incorporate this into our implementations immediately.

**Comment by ApolloZhu** [comment]
Closing this until we figured out the solution


![image](https://user-images.githubusercontent.com/10842684/80994159-4bc15500-8e0a-11ea-8812-e98dfe11dd07.jpeg)

More details: https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf
