### ISSUE TITLE
[Contact Log]Not scrolling to the dates when going back to previous month

### ISSUE THREAD

**Issue by XinyiXiang** [covidsafe/App-iOS#72]
![ezgif com-resize](https://user-images.githubusercontent.com/30137615/80775111-576bfd80-8b24-11ea-8663-4ebfdfde0a30.gif)

Reproduce on ios 13+
- [x] Click on Contact Log

- [x] Tap on any date from the previous month

- [ ] Date scroller goes to the spacing area

**Comment by XinyiXiang** [comment]
(Due to the mismatching dates, current date is set to be May 1st.)

**Comment by cheng-tan** [comment]
@vvvvvicabd I merged the fixes into master branch, can you build against master branch and verify if the issues are fixed?

**Comment by XinyiXiang** [comment]
> @vvvvvicabd I merged the fixes into master branch, can you build against master branch and verify if the issues are fixed?

yes, this has appeared to be fixed

**Comment by cheng-tan** [comment]
thanks for verifying. closing this issue.
