### ISSUE TITLE
Add RSSI threshold for distance estimation

### ISSUE THREAD

**Issue by cheng-tan** [covidsafe/App-iOS#87]

**Comment by justinklchan** [comment]
We check if our device is in the tracetogether smartphone dataset. If it is, we use the RSSI cutoff in the dataset, else we fall back on our magic number -82
https://github.com/covidsafe/App-Android/blob/master/app/src/main/java/edu/uw/covidsafe/ble/BluetoothUtils.java#L152

Here we are just reading the dataset
https://github.com/covidsafe/App-Android/blob/93308c9e38455e3d14c61509bf11b6d53b62824b/app/src/main/java/edu/uw/covidsafe/utils/Constants.java#L257

Dataset
https://github.com/opentrace-community/opentrace-calibration/blob/master/Device%20Data.csv

**Comment by kumpera** [comment]
Let's adopt the Singapore per-device RSSI distance thresholds.
