### ISSUE TITLE
looking for contacts for those rolling this solution out

### ISSUE THREAD

**Issue by brandonvega** [covidsafe/App-iOS#89]
This is not a technical question or issue but I'm looking for functional contacts that might be able to discuss their plans for implementing the CovidSafe solution and how it would be rolled out to the constituents. Any help is appreciated.
-Brandon

**Comment by cheng-tan** [comment]
@brandonvega can you provide more information for your request/use cases etc?

**Comment by cheng-tan** [comment]
Hi @brandonvega, you can also send an email to covidsafe@uw.edu for the questions and issues.

**Comment by cheng-tan** [comment]
Since there's no update for this issue, closing.
