### ISSUE TITLE
Question about Exposure Notification API integration

### ISSUE THREAD

**Issue by mikever** [covidsafe/App-iOS#95]
With the restriction on apps that make use of location tracking, and the limit of 1 Entitlement Profile application per country (or a possible regional/state-by-state approach), what are the plans for CovidSafe's use if the Exposure Notification API?

Are you planning to use it, or are you going to pursue a different direction with cross-platform bluetooth communication?

**Comment by cheng-tan** [comment]
Hi @mikever , BLE implementation has been removed from this app. We have a separate app for BLE(https://github.com/covidsafe/CovidShieldExposure) using Apple Google Exposure notification api.
